### PR TITLE
Feature/hydrus booru

### PR DESCRIPTION
**Pull request by rachmadaniHaryono**
this is feature to enable this program used with hydrus booru on https://github.com/hydrusnetwork/hydrus

### CODE REVIEW

**Comment by deepanprabhu** [comment]
Thanks for the feature and credits.

**Comment by deepanprabhu** [comment]
@rachmadaniHaryono Thank you for helping out with the code. Appreciate your contributions.

The changes related to hydrus are great, but i feel this repo is just for the images api. We can have a separate repo for that, I think you already have one !

Do you want to discuss your changes related to the duck duck go api ? I can merge them in, after talking with you.

What do you think ?

**Comment by rachmadaniHaryono** [comment]
i can reduce this pr to just api change. 

but i request that the `api.py` file to be moved into a folder `duckduckgo_images_api`, so it can be easier for anyone to develop further instead just using a single file. with it is also easier to be packaged and uploaded to pypi.

i will create another pr for example of that

**Comment by deepanprabhu** [comment]
Agree @rachmadaniHaryono , Hey do you want to get in touch via some video chat ? I would love to talk to interested people like you !

**Comment by rachmadaniHaryono** [comment]
sorry i don't have webcam or similar thing

**Comment by deepanprabhu** [comment]
Please submit a PR.

**Pull request closed without merging**
